version: "3"

services:
  backend-api1:
    image: node:lts-alpine
    container_name: backend-api1
    restart: always
    ports:
      - 3001:3001
    working_dir: /backend-api1
    volumes:
      - ./backend-api1:/backend-api1
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SERVICE_API2_ENDPOINT=http://backend-api2:3020/api
    command: npm run dev

  backend-api2:
    image: node:lts-alpine
    container_name: backend-api2
    restart: always
    ports:
      - 3002:3002
    working_dir: /backend-api2
    volumes:
      - ./backend-api2:/backend-api2
    environment:
      - NODE_ENV=development
      - PORT=3002
      - SERVICE_API2_ENDPOINT=http://backend-api2:3020/api
    command: npm run dev

  frontend:
    image: node:lts-alpine
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SERVICE_API2_ENDPOINT=http://backend-api2:3020/api
    command: npm run start