version: "3"

services:
  frontend:
    image: node:lts-alpine
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        build_config: production
    ports:
      - 9000:3000
    environment:
      - PORT=3000
      - SERVICE_API1_ENDPOINT=http://localhost:9010/api
    command: npm run build

  backend-api1:
    image: node:lts-alpine
    container_name: backend-api1
    restart: always
    ports:
      - 9010:3010
    working_dir: /backend-api1
    volumes:
      - ./backend-api1:/backend-api1
    environment:
      - NODE_ENV=development
      - PORT=3010
      - SERVICE_API2_ENDPOINT=http://backend-api2:3020/api
    command: npm run start

  backend-api2:
    image: node:lts-alpine
    container_name: backend-api2
    restart: always
    working_dir: /backend-api2
    volumes:
      - ./backend-api2:/backend-api2
    depends_on:
      - backend-api1
    expose:
      - 3020
    environment:
      - NODE_ENV=development
      - PORT=3020
    command: npm run start